name: Workflow ci

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Post install
        run: npm run postinstall

      - name: Build application
        run: npm run build

      # - name: Install and build
      #   run: |
      #     npm install
      #     npm run postinstall
      #     npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --linux

# jobs:
#   release:
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Install Node.js, NPM and Yarn
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: apt-update
#         if: startsWith(matrix.os, 'ubuntu-latest')
#         run: sudo apt-get update

#       - name: autoremove
#         if: startsWith(matrix.os, 'ubuntu-latest')
#         run: sudo apt autoremove

#       - name: Install libarchive rpm on Linux
#         if: startsWith(matrix.os, 'ubuntu-latest')
#         run: sudo apt-get install libarchive-tools rpm

#       - name: Release Electron app
#         uses: samuelmeuli/action-electron-builder@v1
#         with:
#           github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
#           release: true
