name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Clean npm cache
      #   run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build:renderer

      - name: Build Electron main process
        run: npm run build:main

      - name: Package the app Linux
        run: npx electron-builder --linux

      - name: Package the app Windows
        run: npx electron-builder --win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-artifacts
          path: dist/
